GIT_HASH

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,3 +42,33 @@ jobs:
               HASH=$(git rev-parse --short HEAD)
               echo "Short hash is: $HASH"
               echo "GIT_HASH=$HASH" >> $GITHUB_ENV
+      
+      - name: Trigger Build in JitPack
+        run: |
+              echo "Triggering JitPack build"
+              
+              echo "HASH DETAILS: ${env.GIT_HASH}"
+              
+              PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${env.GIT_HASH}/"
+              PACKAGES_FILE="packages.txt"
+              touch ${PACKAGES_FILE}
+              # Try the URL 6 times before failing
+              count=1
+              until [[ $count -gt 6 ]] || grep -q build.log ${PACKAGES_FILE} ; do
+                echo "Attempt ${count}/6"
+                STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
+                
+                let count+=1
+                if [[ "${STATUS}" -gt 399 ]]; then
+                  sleep 30
+                fi
+              done
+              
+              echo "::group::Files Available"
+              echo $(cat ${PACKAGES_FILE})
+              echo "::endgroup::"
+              
+              if [[ ${STATUS} -gt 399 ]] ; then
+                echo "FAILURE: ${STATUS} response from JitPack"
+                exit 1 
+              fi
